# Generated by Django 4.2.6 on 2024-05-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=50)),
                ('unique_id', models.BigIntegerField(help_text='unique id', unique=True)),
                ('profile_pic', models.ImageField(help_text='Profile picture', upload_to='profile_pics/')),
                ('signature', models.ImageField(help_text='Signature', upload_to='signatures/')),
                ('balance', models.FloatField(help_text='Float number')),
            ],
        ),
    ]
